name = "odic-finance-api"
main = "workers-site/index.js"
compatibility_date = "2025-09-17"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "odic-finance-prod"
database_id = "8d32837b-79b7-4af9-8007-eec44b6244cd"
migrations_dir = "migrations"

