name = "odic-finance-production"
pages_build_output_dir = "public"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "odic-finance-prod"
database_id = "bce6cc34-9924-4203-9f81-665255888dc2"
migrations_dir = "migrations"


