name: Docs PDFs & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # runs on any tag starting with v (e.g., v1.0.0, v2.3.4)

permissions:
  contents: write # required to create a GitHub Release

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install md-to-pdf toolchain
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc

      - name: Build PDFs from docs/*.md
        run: |
          mkdir -p artifacts
          shopt -s nullglob
          for f in docs/*.md; do
            base="$(basename "$f" .md)"
            pandoc "$f" -o "artifacts/${base}.pdf" || echo "Failed to convert $f"
          done
          ls -l artifacts || true

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdfs
          path: artifacts/*.pdf
          if-no-files-found: warn

  create-release:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download PDFs
        uses: actions/download-artifact@v4
        with:
          name: docs-pdfs
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.pdf
          # body_path: docs/Release_Notes.md # optional: include release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
